### ISSUE TITLE
Bug in score parsing (Glide)

### ISSUE THREAD

**Issue by eyesurge** [MolecularAI/maize-contrib#1]
Hi, I've been trying to call maize from reinvent for docking scores with only limited success and a lot of frustration. For each compound sent to docking, maize just returns a result of nan. Having saved my glide outputs, I could verify that there are indeed plenty of scored poses -- but maize seems to have a major problem correctly parsing them.

I spent a few days going down the rabbit hole on this. For background, for each compound, I have Glide generating 4 poses.

Here are the real results for an example compound: [-8.72780234 -8.69718303 -6.2197207  -5.07574205]
And here is what maize spits out: [nan, -8.69718303354234, -6.21972070125591, -5.07574205199212]

Once best_score() is called, it simply takes a min() of the latter array and thus arrives at nan, which is the result the node outputs.

I can of course change the best_score() function to use np.nanmin, in which case it will return an actual value instead of nan, but still the first result is missing. That's especially problematic here because the first docking score is often the lowest. 

```python
@property
    def best_score(self) -> float:
        """The best score among all isomers / conformers"""
        if self.scored and self.n_isomers > 0:
            it = (cast(float, np.nanmin(mol.scores)) for mol in self.molecules if mol.scores is not None)
            return min(it)
        return np.nan
``` 

After much further digging, I deduce that the problem lies in utilties/chem/chem.py, and more specifically somewhere in how IsomerCollection handles RDKit mols. The first conformer for any isomer does not get tags associated with it correctly when it's read in from an SD file. Instead, those properties are associated with the top-level Isomer object. However, interestingly, subsequent Conformers do have the correct tags/properties, so it is always the first score that is nan.

Alas, I couldn't figure out the root cause of the above behavior, so I hope someone can implement a more elegant fix than mine. For now, a manual pull of the prop within scores() works to get the correct lowest scores returned.

```python
@property
    def scores(self) -> NDArray[np.float32]:
        """The scores of the molecule"""
        conf_scores = np.array(
            [conf.get_tag(self.score_tag, np.nan) for conf in self.conformers]
        ).flatten()
        # Hack to correctly get score of first conformer(!)
        # For reasons yet unclear to me, the first score only gets associated with the Isomer object
        # while the first conformers' score tag is set to nan; other conformers have the correct scores
        if np.isnan(conf_scores[0]):
            np.put(conf_scores, 0, self.get_tag(self.score_tag, np.nan))
        iso_scores = np.array(self.get_tag(self.score_tag, [np.nan])).flatten()
        if (
            conf_scores is None
            or len(conf_scores) < len(iso_scores)
            or (~np.isfinite(conf_scores)).all()
        ):
            return iso_scores
        return conf_scores 
```

**Comment by marco-chimfarm** [comment]
Hi, thanks for posting the fix! It actually was quite useful to set our own Glide maize workflow!

How did you manage to save the Glide outputs? I didn't manage to save them (even with the "--keep" option or the "cleanup_temp=False" flag) and it might help with troubleshooting this issue.

**Comment by eyesurge** [comment]
> Hi, thanks for posting the fix! It actually was quite useful to set our own Glide maize workflow!
> 
> How did you manage to save the Glide outputs? I didn't manage to save them (even with the "--keep" option or the "cleanup_temp=False" flag) and it might help with troubleshooting this issue.

In the maize.toml global config, so that the outputs don't go to /tmp, I have:
```shell
scratch = "/scratch"
``` 

In the reinvent input, I use:
```python
[[stage.scoring.component.Maize.endpoint]]
name = "MAIZE docking Glide"
...
params.config = "maize.toml"
params.debug = true
params.keep = true
``` 

With the setup above, I find the inputs/outputs are retained in /scratch/graph-Docking-Glide-###/node-dock.

**Comment by tlhr** [comment]
Hi Both, sorry for the late reply on this. I have updated both this repo and core `maize`, this should also have fixed the NaN score issue. Please let me know if this worked for you!

**Comment by eyesurge** [comment]
> Hi Both, sorry for the late reply on this. I have updated both this repo and core `maize`, this should also have fixed the NaN score issue. Please let me know if this worked for you!

Hi Thomas, the latest version seems to have fixed the NaN issue, thank you!

```
2024-08-22 23:10:19,120 |     INFO |              rnv | Sending 8 scores: [-9.71733738128091, -8.83922691963052, -7.00621415017166, -7.37792639941428, -9.42370731574149, -10.1247642960903, -8.25267965147064, -8.98783265438632]
```
